appname:
  prompt: Application Name

description:
  prompt: Application description

localhostname:
  prompt: Local Hostname (localhost)
  default: localhost


dbname:
  prompt: Database Name

dbuser:
  prompt: Database User

dbpasswd:
  prompt: Database User password

