port: %dev-port%
local-hostname: %local-hostname%
publics:
  /*: public

database: false

db-user: %dbuser%
db-password: %dbpasswd% # should encode the password as the example below
# db-password: '{SHA}5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8'
db-name: %dbname%

session: false
session-cookie-domain: %dev-session-cookie-domain%


prod:
  port: 3000
  http2: true
  session-cookie-domain: %production-session-cookie-domain%
  publics:
    /*: public/build/es6-bundled
