port: %dev-port%
local-hostname: %local-hostname%


database: false

db-user: %dbuser%
db-password: %dbpasswd%
# db-password: '{SHA}5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8'
db-name: %dbname%

session: false
session-cookie-domain: %dev-session-cookie-domain% # IMPORTANT


prod:
  port: 3000 # IMPORTANT
  session-cookie-domain: %production-session-cookie-domain% # IMPORTANT
  public-directory: public/build/ # NEED
